### ISSUE TITLE
The OpenVPN process exits unexpectedly when using the DCO kernel module

### ISSUE THREAD

**Issue by kEu3lWPoZ8XRv1O3hEt5xSQQJM0TvH2k** [OpenVPN/openvpn#542]
**Describe the bug**

Good afternoon!

We encountered such a problem on our installation of an OpenVPN server using the DCO core module.
The problem causes the OpenVPN process to crash with disconnecting of all clients connected to OpenVPN. The problem is critical in the conditions of production.

Initial issue's comment inside the ovpn-dco repository: https://github.com/OpenVPN/ovpn-dco/issues/50#issuecomment-2071953786

**To Reproduce**

- Occurrence: varies (ranging from "very rare" to several cases per day).
- Steps to reproduce: unknown. The problem manifests itself on the OpenVPN cluster, each node of which simultaneously serves 500-1500 clients around the clock.

**Expected behavior**
The OpenVPN process does not crash due to a single client's key context initialization error.

**Version information (please complete the following information):**
- OpenVPN service version: `2.6.3-1 (deb12u2)`.
- The Linux distribution used: `Debian Bookworm (v12.5)`.
- OpenVPN DCO module version: compiled from the source code (`master` from
2024.04.16).

**Additional context**

Example of an OpenVPN logs during a crash (#1):

```
2024-04-17 13:58:41 us=532843 client.name123/client_source_ip_v4_address:client_source_port peer-id=321 dco_new_key: netlink reports object not found, ovpn-dco unloaded?
2024-04-17 13:58:41 us=532876 client.name123/client_source_ip_v4_address:client_source_port peer-id=321 dco_new_key: failed to send netlink message: No such file or directory (-2)
2024-04-17 13:58:41 us=532912 client.name123/client_source_ip_v4_address:client_source_port peer-id=321 Impossible to install key material in DCO: No such file or directory
2024-04-17 13:58:41 us=532936 client.name123/client_source_ip_v4_address:client_source_port peer-id=321 Exiting due to fatal error
2024-04-17 13:58:41 us=532985 client.name123/client_source_ip_v4_address:client_source_port peer-id=321 Closing DCO interface
```

Example of an OpenVPN logs during a crash (#2):

```
2024-04-17 16:05:34 us=166246 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 peer info: IV_SSL=OpenSSL_3.XXX
2024-04-17 16:05:34 us=166386 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 UDPv4 WRITE [311] to [AF_INET]client_source_ip_v4_address:client_source_port: P_CONTROL_V1 kid=1 [ ] pid=1382 DATA len=297
2024-04-17 16:05:34 us=171898 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 UDPv4 READ [74] from [AF_INET]client_source_ip_v4_address:client_source_port: P_ACK_V1 kid=1 [ ] DATA len=64
2024-04-17 16:05:34 us=172148 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 UDPv4 READ [74] from [AF_INET]client_source_ip_v4_address:client_source_port: P_ACK_V1 kid=1 [ ] DATA len=64
2024-04-17 16:05:34 us=172201 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 256 bit ED25519, signature: ED25519
2024-04-17 16:05:34 us=172294 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 dco_install_key: peer_id=465 keyid=1, currently 1 keys installed
2024-04-17 16:05:34 us=172320 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 dco_new_key: slot 1, key-id 1, peer-id 465, cipher AES-256-GCM
2024-04-17 16:05:34 us=172384 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 dco_new_key: netlink reports object not found, ovpn-dco unloaded?
2024-04-17 16:05:34 us=172408 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 dco_new_key: failed to send netlink message: No such file or directory (-2)
2024-04-17 16:05:34 us=172432 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 Impossible to install key material in DCO: No such file or directory
2024-04-17 16:05:34 us=172450 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 Exiting due to fatal error
2024-04-17 16:05:34 us=172513 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 Closing DCO interface
2024-04-17 16:05:34 us=172536 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 net_addr_v4_del: ip_v4_address dev tun0
2024-04-17 16:05:34 us=173286 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 sitnl_send: checking for received messages
2024-04-17 16:05:34 us=173351 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 sitnl_send: rtnl: received 36 bytes
2024-04-17 16:05:34 us=173384 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 net_addr_v6_del: ip_v6_address/112 dev tun0
2024-04-17 16:05:34 us=173510 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 sitnl_send: checking for received messages
2024-04-17 16:05:34 us=173532 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 sitnl_send: rtnl: received 36 bytes
2024-04-17 16:05:34 us=173551 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 close_tun_dco
2024-04-17 16:05:34 us=173581 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 net_iface_del: delete tun0
2024-04-17 16:05:34 us=370712 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 sitnl_send: checking for received messages
2024-04-17 16:05:34 us=370770 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 sitnl_send: rtnl: received 36 bytes

--- OpenVPN process restart goes here
```

Crash reason:

https://github.com/OpenVPN/openvpn/blob/32e6586687a548174b88b64fe54bfae6c74d4c19/src/openvpn/ssl.c#L1361
^ `M_FATAL` causes the process to crash after an unsuccessful attempt to install key material in the DCO module.

Confirmation:

https://github.com/OpenVPN/openvpn/blob/master/src/openvpn/error.h#L142
^ Calling the `msg()` procedure with the `M_FATAL` flag results in an emergency (code `1`) shutdown of the process.

Problem fixing scheme:
- Replace `M_FATAL` flag with `M_WARN` in the problem source code location
- Convert the `init_key_contexts` procedure into a function that returns `bool`
- Return `false` inside `init_key_context` in case of failure, otherwise return `true`
- Handle in all places (only one was found) using `init_key_context`, the case of returning `false` (failed initialization of the key context)
- Monitor the correct destruction of execution contexts (in order to avoid memory leaks) in all affected code sections

Patch with fix (spot):
[diff.patch](https://github.com/OpenVPN/openvpn/files/15076359/diff.patch)

Patch with fix (full):
[full_diff.patch](https://github.com/OpenVPN/openvpn/files/15076357/full_diff.patch)

`dmesg` logs before fixing:

```
2024-04-17T16:05:27.606710+03:00 openvpn kernel: [69250.222529] ovpn_udp_encap_recv: received data from unknown peer (id: 465)
2024-04-17T16:05:27.950720+03:00 openvpn kernel: [69250.565701] ovpn_udp_encap_recv: received data from unknown peer (id: 465)
2024-04-17T16:05:27.950858+03:00 openvpn kernel: [69250.566003] ovpn_udp_encap_recv: received data from unknown peer (id: 465)
2024-04-17T16:05:28.606691+03:00 openvpn kernel: [69251.220475] ovpn_udp_encap_recv: received data from unknown peer (id: 465)
2024-04-17T16:05:28.606723+03:00 openvpn kernel: [69251.220713] ovpn_udp_encap_recv: received data from unknown peer (id: 465)
2024-04-17T16:05:30.850734+03:00 openvpn kernel: [69253.463873] tun0: deleting peer with id 670, reason 1
2024-04-17T16:05:32.674766+03:00 openvpn kernel: [69255.289142] net_ratelimit: 56 callbacks suppressed
2024-04-17T16:05:32.674919+03:00 openvpn kernel: [69255.289150] ovpn_aead_decrypt: decrypt failed: -74
2024-04-17T16:05:32.674943+03:00 openvpn kernel: [69255.289499] ovpn_decrypt_one: error during decryption for peer 611, key-id 0: -74
2024-04-17T16:05:32.694773+03:00 openvpn kernel: [69255.308232] ovpn_aead_decrypt: decrypt failed: -74
2024-04-17T16:05:32.695002+03:00 openvpn kernel: [69255.308469] ovpn_decrypt_one: error during decryption for peer 611, key-id 0: -74
2024-04-17T16:05:32.695071+03:00 openvpn kernel: [69255.308720] ovpn_aead_decrypt: decrypt failed: -74
2024-04-17T16:05:32.695118+03:00 openvpn kernel: [69255.308974] ovpn_decrypt_one: error during decryption for peer 611, key-id 0: -74
2024-04-17T16:05:32.695233+03:00 openvpn kernel: [69255.309238] ovpn_aead_decrypt: decrypt failed: -74
2024-04-17T16:05:32.695308+03:00 openvpn kernel: [69255.309506] ovpn_decrypt_one: error during decryption for peer 611, key-id 0: -74
2024-04-17T16:05:32.695348+03:00 openvpn kernel: [69255.309820] ovpn_aead_decrypt: decrypt failed: -74
2024-04-17T16:05:32.695397+03:00 openvpn kernel: [69255.310104] ovpn_decrypt_one: error during decryption for peer 611, key-id 0: -74
2024-04-17T16:05:34.190782+03:00 openvpn kernel: [69256.805266] tun0: deleting peer with id 433, reason 0
2024-04-17T16:05:34.190799+03:00 openvpn kernel: [69256.805276] tun0: deleting peer with id 447, reason 0
2024-04-17T16:05:34.190801+03:00 openvpn kernel: [69256.805286] tun0: deleting peer with id 38, reason 0
2024-04-17T16:05:34.190802+03:00 openvpn kernel: [69256.805290] tun0: deleting peer with id 463, reason 0
2024-04-17T16:05:34.190805+03:00 openvpn kernel: [69256.805297] tun0: deleting peer with id 553, reason 0
2024-04-17T16:05:34.190808+03:00 openvpn kernel: [69256.805302] tun0: deleting peer with id 530, reason 0
2024-04-17T16:05:34.190809+03:00 openvpn kernel: [69256.805305] tun0: deleting peer with id 398, reason 0
2024-04-17T16:05:34.190811+03:00 openvpn kernel: [69256.805309] tun0: deleting peer with id 389, reason 0
2024-04-17T16:05:34.190812+03:00 openvpn kernel: [69256.805315] tun0: deleting peer with id 272, reason 0
2024-04-17T16:05:34.190814+03:00 openvpn kernel: [69256.805324] tun0: deleting peer with id 569, reason 0
2024-04-17T16:05:34.190815+03:00 openvpn kernel: [69256.805331] tun0: deleting peer with id 86, reason 0
2024-04-17T16:05:34.190816+03:00 openvpn kernel: [69256.805339] tun0: deleting peer with id 202, reason 0
2024-04-17T16:05:34.190818+03:00 openvpn kernel: [69256.805345] tun0: deleting peer with id 236, reason 0
2024-04-17T16:05:34.190820+03:00 openvpn kernel: [69256.805352] tun0: deleting peer with id 391, reason 0
2024-04-17T16:05:34.190821+03:00 openvpn kernel: [69256.805356] tun0: deleting peer with id 368, reason 0
2024-04-17T16:05:34.190822+03:00 openvpn kernel: [69256.805360] tun0: deleting peer with id 208, reason 0
2024-04-17T16:05:34.190823+03:00 openvpn kernel: [69256.805369] tun0: deleting peer with id 642, reason 0
2024-04-17T16:05:34.190824+03:00 openvpn kernel: [69256.805379] tun0 (unregistering): deleting peer with id 352, reason 0
2024-04-17T16:05:34.190825+03:00 openvpn kernel: [69256.805448] tun0 (unregistering): deleting peer with id 687, reason 0
2024-04-17T16:05:34.190826+03:00 openvpn kernel: [69256.805454] tun0 (unregistering): deleting peer with id 575, reason 0
```

OpenVPN logs after correction:

```
2024-04-19 18:56:23 us=669145 client.name123/client_source_ip_v4_address:client_source_port peer-id=475 peer info: IV_SSO=XXX
2024-04-19 18:56:23 us=669315 client.name123/client_source_ip_v4_address:client_source_port peer-id=475 UDPv4 WRITE [315] to [AF_INET]client_source_ip_v4_address:client_source_port: P_CONTROL_V1 kid=1 [ ] pid=1638 DATA len=301
2024-04-19 18:56:23 us=674261 client.name123/client_source_ip_v4_address:client_source_port peer-id=475 UDPv4 READ [74] from [AF_INET]client_source_ip_v4_address:client_source_port: P_ACK_V1 kid=1 [ ] DATA len=64
2024-04-19 18:56:23 us=676230 client.name123/client_source_ip_v4_address:client_source_port peer-id=475 UDPv4 READ [78] from [AF_INET]client_source_ip_v4_address:client_source_port: P_ACK_V1 kid=1 [ ] DATA len=68
2024-04-19 18:56:23 us=676314 client.name123/client_source_ip_v4_address:client_source_port peer-id=475 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 256 bit ED25519, signature: ED25519
2024-04-19 18:56:23 us=676498 client.name123/client_source_ip_v4_address:client_source_port peer-id=475 dco_install_key: peer_id=475 keyid=1, currently 1 keys installed
2024-04-19 18:56:23 us=676538 client.name123/client_source_ip_v4_address:client_source_port peer-id=475 dco_new_key: slot 1, key-id 1, peer-id 475, cipher AES-256-GCM
2024-04-19 18:56:23 us=676643 client.name123/client_source_ip_v4_address:client_source_port peer-id=475 dco_new_key: netlink reports object not found, ovpn-dco unloaded?
2024-04-19 18:56:23 us=676674 client.name123/client_source_ip_v4_address:client_source_port peer-id=475 dco_new_key: failed to send netlink message: No such file or directory (-2)
2024-04-19 18:56:23 us=676694 client.name123/client_source_ip_v4_address:client_source_port peer-id=475 Impossible to install key material in DCO: No such file or directory
2024-04-19 18:56:23 us=676712 client.name123/client_source_ip_v4_address:client_source_port peer-id=475 TLS Error: Could not initialize key contexts
2024-04-19 18:56:23 us=676729 client.name123/client_source_ip_v4_address:client_source_port peer-id=475 TLS Error: generate_key_expansion failed
2024-04-19 18:56:23 us=676746 client.name123/client_source_ip_v4_address:client_source_port peer-id=475 TLS Error: generate_key_expansion failed
2024-04-19 18:56:24 us=2153 dco_get_peer_stats_multi
2024-04-19 18:56:24 us=2917 dco_parse_peer_multi: parsing message...
2024-04-19 18:56:24 us=2961 dco_update_peer_stat / dco_read_bytes: 2474690
2024-04-19 18:56:24 us=2981 dco_update_peer_stat / dco_write_bytes: 134735523
2024-04-19 18:56:24 us=2998 dco_update_peer_stat / tun_read_bytes: 1965650
2024-04-19 18:56:24 us=3015 NOTE: --mute triggered...
```

`dmesg` logs after fixing:

```
2024-04-19T18:56:23.002300+03:00 openvpn kernel: [81066.439726] tun0: ovpn_decrypt_one: ping receiv
ed from peer with id 320
2024-04-19T18:56:23.046312+03:00 openvpn kernel: [81066.487702] tun0: ovpn_peer_ping: sending ping to peer 310
2024-04-19T18:56:23.046326+03:00 openvpn kernel: [81066.487703] tun0: ovpn_peer_ping: sending ping to peer 9
2024-04-19T18:56:23.046330+03:00 openvpn kernel: [81066.487702] tun0: ovpn_peer_ping: sending ping to peer 84
2024-04-19T18:56:23.046333+03:00 openvpn kernel: [81066.487719] tun0: ovpn_peer_ping: sending ping to peer 14
2024-04-19T18:56:23.050288+03:00 openvpn kernel: [81066.491703] tun0: ovpn_peer_ping: sending ping to peer 311
2024-04-19T18:56:23.058293+03:00 openvpn kernel: [81066.496184] tun0: ovpn_decrypt_one: ping received from peer with id 524
2024-04-19T18:56:23.118301+03:00 openvpn kernel: [81066.556824] tun0: ovpn_decrypt_one: ping received from peer with id 653
2024-04-19T18:56:23.122283+03:00 openvpn kernel: [81066.560031] tun0: ovpn_decrypt_one: ping received from peer with id 90
2024-04-19T18:56:23.218286+03:00 openvpn kernel: [81066.658509] tun0: ovpn_decrypt_one: ping received from peer with id 212
2024-04-19T18:56:23.222284+03:00 openvpn kernel: [81066.661884] tun0: ovpn_decrypt_one: ping received from peer with id 290
2024-04-19T18:56:23.286309+03:00 openvpn kernel: [81066.725031] tun0: ovpn_decrypt_one: ping received from peer with id 651
2024-04-19T18:56:23.306312+03:00 openvpn kernel: [81066.743687] tun0: ovpn_peer_ping: sending ping to peer 370
2024-04-19T18:56:23.306323+03:00 openvpn kernel: [81066.743688] tun0: ovpn_peer_ping: sending ping to peer 277
2024-04-19T18:56:23.306328+03:00 openvpn kernel: [81066.743701] tun0: ovpn_peer_ping: sending ping to peer 628
2024-04-19T18:56:23.306330+03:00 openvpn kernel: [81066.747668] tun0: ovpn_peer_ping: sending ping to peer 653
2024-04-19T18:56:23.306331+03:00 openvpn kernel: [81066.747688] tun0: ovpn_peer_ping: sending ping to peer 290
2024-04-19T18:56:23.358302+03:00 openvpn kernel: [81066.796182] tun0: ovpn_decrypt_one: ping received from peer with id 493
2024-04-19T18:56:23.374312+03:00 openvpn kernel: [81066.814880] tun0: ovpn_decrypt_one: ping received from peer with id 96
2024-04-19T18:56:23.482285+03:00 openvpn kernel: [81066.919873] tun0: ovpn_decrypt_one: ping received from peer with id 395
2024-04-19T18:56:23.486290+03:00 openvpn kernel: [81066.925117] tun0: ovpn_decrypt_one: ping received from peer with id 361
2024-04-19T18:56:23.526293+03:00 openvpn kernel: [81066.966186] tun0: ovpn_decrypt_one: ping received from peer with id 502
2024-04-19T18:56:23.558329+03:00 openvpn kernel: [81066.999665] tun0: ovpn_peer_ping: sending ping to peer 493
2024-04-19T18:56:23.558341+03:00 openvpn kernel: [81066.999664] tun0: ovpn_peer_ping: sending ping to peer 23
2024-04-19T18:56:23.558343+03:00 openvpn kernel: [81066.999665] tun0: ovpn_peer_ping: sending ping to peer 502
2024-04-19T18:56:23.558346+03:00 openvpn kernel: [81066.999665] tun0: ovpn_peer_ping: sending ping to peer 219
2024-04-19T18:56:23.558347+03:00 openvpn kernel: [81066.999667] tun0: ovpn_peer_ping: sending ping to peer 361
2024-04-19T18:56:23.558349+03:00 openvpn kernel: [81066.999667] tun0: ovpn_peer_ping: sending ping to peer 96
2024-04-19T18:56:23.558351+03:00 openvpn kernel: [81066.999679] tun0: ovpn_peer_ping: sending ping to peer 395
```

Please pay attention to this problem. I will monitor this issue and respond if necessary.
Thanks!

**Comment by ordex** [comment]
Thanks for the report!
Any clue why that key installation is failing in the first place?
Can you share a longer log including lines since the time the client connected to the server?

My guess is that DCO is not finding the peer to install the key for.
If this is the case, then there is a bug *before* the key installation and the failed key installation is just a symptom.

**Comment by ordex** [comment]
note: I am deleting your post in the ovpn-dco ticket to avoid confusion.

**Comment by dsommers** [comment]
I would say this is issue is two-fold:

1. The DCO module not getting the right keys installed properly
2. The OpenVPN process halting.  This may be fine for the client side, but not for the server side (where other connected clients may not have issues)

**Comment by kEu3lWPoZ8XRv1O3hEt5xSQQJM0TvH2k** [comment]
>Any clue why that key installation is failing in the first place?


@ordex As far as I understand, the error when initializing the key context is primary, since nothing unusual happens in the `dmesg` logs. For example, the `ovpn-dco` module is not being unloaded. There are just some errors related to data encryption. The verification was carried out both in the normal operation mode of the DCO module and with the module compiled in debugging mode. No changes were detected in `dmesg`, the module is not being unloaded.

The OpenVPN process itself is being completed, the operation of the `ovpn-dco` module remains unchanged.

The issue contains logs from `dmesg` and OpenVPN logs during the service crash. The time is the same, you can make sure that the `ovpn-dco` module does not really unload during the crash:


`dmesg` logs before fixing:

```
2024-04-17T16:05:27.606710+03:00 openvpn kernel: [69250.222529] ovpn_udp_encap_recv: received data from unknown peer (id: 465)
2024-04-17T16:05:27.950720+03:00 openvpn kernel: [69250.565701] ovpn_udp_encap_recv: received data from unknown peer (id: 465)
2024-04-17T16:05:27.950858+03:00 openvpn kernel: [69250.566003] ovpn_udp_encap_recv: received data from unknown peer (id: 465)
2024-04-17T16:05:28.606691+03:00 openvpn kernel: [69251.220475] ovpn_udp_encap_recv: received data from unknown peer (id: 465)
2024-04-17T16:05:28.606723+03:00 openvpn kernel: [69251.220713] ovpn_udp_encap_recv: received data from unknown peer (id: 465)
2024-04-17T16:05:30.850734+03:00 openvpn kernel: [69253.463873] tun0: deleting peer with id 670, reason 1
2024-04-17T16:05:32.674766+03:00 openvpn kernel: [69255.289142] net_ratelimit: 56 callbacks suppressed
2024-04-17T16:05:32.674919+03:00 openvpn kernel: [69255.289150] ovpn_aead_decrypt: decrypt failed: -74
2024-04-17T16:05:32.674943+03:00 openvpn kernel: [69255.289499] ovpn_decrypt_one: error during decryption for peer 611, key-id 0: -74
2024-04-17T16:05:32.694773+03:00 openvpn kernel: [69255.308232] ovpn_aead_decrypt: decrypt failed: -74
2024-04-17T16:05:32.695002+03:00 openvpn kernel: [69255.308469] ovpn_decrypt_one: error during decryption for peer 611, key-id 0: -74
2024-04-17T16:05:32.695071+03:00 openvpn kernel: [69255.308720] ovpn_aead_decrypt: decrypt failed: -74
2024-04-17T16:05:32.695118+03:00 openvpn kernel: [69255.308974] ovpn_decrypt_one: error during decryption for peer 611, key-id 0: -74
2024-04-17T16:05:32.695233+03:00 openvpn kernel: [69255.309238] ovpn_aead_decrypt: decrypt failed: -74
2024-04-17T16:05:32.695308+03:00 openvpn kernel: [69255.309506] ovpn_decrypt_one: error during decryption for peer 611, key-id 0: -74
2024-04-17T16:05:32.695348+03:00 openvpn kernel: [69255.309820] ovpn_aead_decrypt: decrypt failed: -74
2024-04-17T16:05:32.695397+03:00 openvpn kernel: [69255.310104] ovpn_decrypt_one: error during decryption for peer 611, key-id 0: -74
2024-04-17T16:05:34.190782+03:00 openvpn kernel: [69256.805266] tun0: deleting peer with id 433, reason 0
2024-04-17T16:05:34.190799+03:00 openvpn kernel: [69256.805276] tun0: deleting peer with id 447, reason 0
2024-04-17T16:05:34.190801+03:00 openvpn kernel: [69256.805286] tun0: deleting peer with id 38, reason 0
2024-04-17T16:05:34.190802+03:00 openvpn kernel: [69256.805290] tun0: deleting peer with id 463, reason 0
2024-04-17T16:05:34.190805+03:00 openvpn kernel: [69256.805297] tun0: deleting peer with id 553, reason 0
2024-04-17T16:05:34.190808+03:00 openvpn kernel: [69256.805302] tun0: deleting peer with id 530, reason 0
2024-04-17T16:05:34.190809+03:00 openvpn kernel: [69256.805305] tun0: deleting peer with id 398, reason 0
2024-04-17T16:05:34.190811+03:00 openvpn kernel: [69256.805309] tun0: deleting peer with id 389, reason 0
2024-04-17T16:05:34.190812+03:00 openvpn kernel: [69256.805315] tun0: deleting peer with id 272, reason 0
2024-04-17T16:05:34.190814+03:00 openvpn kernel: [69256.805324] tun0: deleting peer with id 569, reason 0
2024-04-17T16:05:34.190815+03:00 openvpn kernel: [69256.805331] tun0: deleting peer with id 86, reason 0
2024-04-17T16:05:34.190816+03:00 openvpn kernel: [69256.805339] tun0: deleting peer with id 202, reason 0
2024-04-17T16:05:34.190818+03:00 openvpn kernel: [69256.805345] tun0: deleting peer with id 236, reason 0
2024-04-17T16:05:34.190820+03:00 openvpn kernel: [69256.805352] tun0: deleting peer with id 391, reason 0
2024-04-17T16:05:34.190821+03:00 openvpn kernel: [69256.805356] tun0: deleting peer with id 368, reason 0
2024-04-17T16:05:34.190822+03:00 openvpn kernel: [69256.805360] tun0: deleting peer with id 208, reason 0
2024-04-17T16:05:34.190823+03:00 openvpn kernel: [69256.805369] tun0: deleting peer with id 642, reason 0
2024-04-17T16:05:34.190824+03:00 openvpn kernel: [69256.805379] tun0 (unregistering): deleting peer with id 352, reason 0
2024-04-17T16:05:34.190825+03:00 openvpn kernel: [69256.805448] tun0 (unregistering): deleting peer with id 687, reason 0
2024-04-17T16:05:34.190826+03:00 openvpn kernel: [69256.805454] tun0 (unregistering): deleting peer with id 575, reason 0
```


Example of an OpenVPN logs during a crash (#2):

```
2024-04-17 16:05:34 us=166246 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 peer info: IV_SSL=OpenSSL_3.XXX
2024-04-17 16:05:34 us=166386 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 UDPv4 WRITE [311] to [AF_INET]client_source_ip_v4_address:client_source_port: P_CONTROL_V1 kid=1 [ ] pid=1382 DATA len=297
2024-04-17 16:05:34 us=171898 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 UDPv4 READ [74] from [AF_INET]client_source_ip_v4_address:client_source_port: P_ACK_V1 kid=1 [ ] DATA len=64
2024-04-17 16:05:34 us=172148 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 UDPv4 READ [74] from [AF_INET]client_source_ip_v4_address:client_source_port: P_ACK_V1 kid=1 [ ] DATA len=64
2024-04-17 16:05:34 us=172201 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 256 bit ED25519, signature: ED25519
2024-04-17 16:05:34 us=172294 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 dco_install_key: peer_id=465 keyid=1, currently 1 keys installed
2024-04-17 16:05:34 us=172320 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 dco_new_key: slot 1, key-id 1, peer-id 465, cipher AES-256-GCM
2024-04-17 16:05:34 us=172384 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 dco_new_key: netlink reports object not found, ovpn-dco unloaded?
2024-04-17 16:05:34 us=172408 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 dco_new_key: failed to send netlink message: No such file or directory (-2)
2024-04-17 16:05:34 us=172432 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 Impossible to install key material in DCO: No such file or directory
2024-04-17 16:05:34 us=172450 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 Exiting due to fatal error
2024-04-17 16:05:34 us=172513 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 Closing DCO interface
2024-04-17 16:05:34 us=172536 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 net_addr_v4_del: ip_v4_address dev tun0
2024-04-17 16:05:34 us=173286 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 sitnl_send: checking for received messages
2024-04-17 16:05:34 us=173351 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 sitnl_send: rtnl: received 36 bytes
2024-04-17 16:05:34 us=173384 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 net_addr_v6_del: ip_v6_address/112 dev tun0
2024-04-17 16:05:34 us=173510 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 sitnl_send: checking for received messages
2024-04-17 16:05:34 us=173532 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 sitnl_send: rtnl: received 36 bytes
2024-04-17 16:05:34 us=173551 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 close_tun_dco
2024-04-17 16:05:34 us=173581 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 net_iface_del: delete tun0
2024-04-17 16:05:34 us=370712 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 sitnl_send: checking for received messages
2024-04-17 16:05:34 us=370770 client.name123/client_source_ip_v4_address:client_source_port peer-id=465 sitnl_send: rtnl: received 36 bytes

--- OpenVPN process restart goes here
```

**Comment by ordex** [comment]
@kEu3lWPoZ8XRv1O3hEt5xSQQJM0TvH2k I was hoping to get an earlier log from OpenVPN (not kernel/ovpn-dco log) that shows the full connection of the client (when also the dco_new_peer is invoked).
I also don't expect to see other errors, but  I just want to see the sequence of events.

**Comment by ordex** [comment]
as you can see at the very beginning of the dmesg log:
`2024-04-17T16:05:28.606723+03:00 openvpn kernel: [69251.220713] ovpn_udp_encap_recv: received data from unknown peer (id: 465)`
peer 465 was already unknown.
This means this peer was removed at some point earlier on or this peer was never added at all. But can't say which one is true with the log starting there.
I hope I managed to convey my point

**Comment by kEu3lWPoZ8XRv1O3hEt5xSQQJM0TvH2k** [comment]
@ordex I will try to provide all the necessary information as soon as possible.

**Comment by kEu3lWPoZ8XRv1O3hEt5xSQQJM0TvH2k** [comment]
Thanks for the reply, @ordex.

I will try to send you the logs tomorrow (April 25th).

**Comment by kEu3lWPoZ8XRv1O3hEt5xSQQJM0TvH2k** [comment]
Good afternoon, @ordex!

Thanks for waiting. I've prepared the information you requested. There are filtered samples from openvpn.log (OpenVPN service logs) and kern.log (kernel logs).

Filtering was performed by the peer ID starting at midnight and ending with the fall of OpenVPN. I have tried to keep as much relevant information as possible.


Here they are:
[kern.log](https://github.com/OpenVPN/openvpn/files/15118904/kern.log)
[openvpn.log](https://github.com/OpenVPN/openvpn/files/15118906/openvpn.log)


Is there anything else I can do to help?

**Comment by ordex** [comment]
Thanks a lot! This looks interesting.
Allow me some time to dig into the text and I'll report back

**Comment by kEu3lWPoZ8XRv1O3hEt5xSQQJM0TvH2k** [comment]
Good afternoon, @ordex!

Can you tell me, please, if there is any news?

Thanks!

**Comment by ordex** [comment]
Sorry, not yet. I'm quite busy with the upstream submission and I haven't had time to dig deep enough.
I should be able to jump on this next week.

**Comment by evant89** [comment]
> Sorry, not yet. I'm quite busy with the upstream submission and I haven't had time to dig deep enough. I should be able to jump on this next week.

Greetings. 
We also face this problem. Are there any known solutions? Or, perhaps, are planned?

**Comment by ordex** [comment]
still on the todo, sorry

**Comment by AharonFeinstein** [comment]
I think its possible this issue is related to the openvpn status (--status) file.  I first found connection when I noticed my logrotation was accidently rotating the status log (*.log), the timestamps of the errors coincided with the rotation.  After fixing that the errors went down, but still happen occasionally.  I suspect it is casued by openvpn itself updating the file, if the timing is just right, it conficts with DCO reading the file and caused the problem.

**Comment by ordex** [comment]
Hi @AharonFeinstein thanks for chiming in, however the provided logs clearly show that the issue is happening due to some other DCO loic failing, unrelated to the status file.
I also believe there is no status file configured in these setups.

**Comment by cron2** [comment]
I wager we might have fixed this by means of #945 - we had this problem with kernel and userland getting out of sync regarding peer status if kernel notifications get lost in our simplistic userland implementation.

This has been fixed for 2.7 / new-in-kernel-DCO since half a year or so, and is now also fixed for 2.6 / out-of-tree-ovpn-v2, to be released as part of 2.6.20 today.

Please re-test with 2.6.20 and report if this is now fixed.  Sorry for taking so long.

**Comment by InputOutputZ** [comment]
> I wager we might have fixed this by means of [#945](https://github.com/OpenVPN/openvpn/pull/945) - we had this problem with kernel and userland getting out of sync regarding peer status if kernel notifications get lost in our simplistic userland implementation.
> 
> This has been fixed for 2.7 / new-in-kernel-DCO since half a year or so, and is now also fixed for 2.6 / out-of-tree-ovpn-v2, to be released as part of 2.6.20 today.
> 
> Please re-test with 2.6.20 and report if this is now fixed. Sorry for taking so long.

I think this issue still happens but very rarely in 2.7.5 release. I experience the out of sync every now and then and mostly when device sits idle for a long time, like overnight.  

I sat following:-
```
push "explicit-exit-notify 1"
explicit-exit-notify 1
```

and reduced keepalive timeout from 10 120 to 5 30 to avoid the potential of reconnection collision with already dying connection and hope to see this issue rectified. Although not sure, if I my understanding wasn't correct, any recommendation would be very much appreciated, with thanks.

**Comment by cron2** [comment]
Please include a log file with `verb 7` displaying the problem.  Without a log, it did not happen.

**Comment by InputOutputZ** [comment]
> Please include a log file with `verb 7` displaying the problem. Without a log, it did not happen.

I can't reproduce it, as it happens rarely, the only trace I found relevant to OpenVPN process in log was this:-

Jul 22 00:30:00 server openvpn[411934]: [client details redacted]… CC-EEN exit message received by peer
Jul 22 00:30:00 server kernel: tun0: deleting peer with id 1, reason 2

**Comment by schwabe** [comment]
@InputOutputZ that logline says that the client explicitly the server that it is terminating. If that is unexpected you need to look on the client why that is quitting.

**Comment by InputOutputZ** [comment]
> [@InputOutputZ](https://github.com/InputOutputZ) that logline says that the client explicitly the server that it is terminating. If that is unexpected you need to look on the client why that is quitting.

I looked at the client side, Android using OpenVPN3 CPP library, in log it doesn't show any crash or segfault. Reviewed my code logic and it's working as expected, when server unexpectedly terminates the OpenVPN connection, I notify the User and stop reconnecting attempts. 

When normally/explicitly client disconnects this is what I get with reason 1, that is 5 lines of log unlike the log when the issue occurs:-

```
Jul 22 13:14:14 server openvpn[2009483]: [client details redacted] CC-EEN exit message received by peer
Jul 22 13:14:14 server openvpn[2009483]: [client details redacted] Delayed exit in 5 seconds
Jul 22 13:14:19 server openvpn[2009483]: [client details redacted] SIGTERM[soft,delayed-exit] received, client-instance exiting
Jul 22 13:14:19 server openvpn[2009483]: ovpn_handle_peer: received data for a non-existing peer 1
Jul 22 13:14:19 server kernel: tun0: deleting peer with id 1, reason 1
```

Why today in the morning at 00:30, the server uncleanly disconencted and terminated connection with 3 lines of log with reason 2, also :-

```
Jul 22 00:30:00 server openvpn[2009483]: process_incoming_dco: received peer expired notification for peer-id 1
Jul 22 00:30:00 server kernel: tun0: deleting peer with id 1, reason 2
Jul 22 00:30:00 server openvpn[2009483]: [client details redacted] Inactivity timeout (--ping-restart), restarting
```

While I'm running the same OpenVPN server, previous days it didn't happen. that's why still thinking in the time window of graceful Android OpenVPN disconnecting probably due to WIFI/Celular signal loss and OpenVPN client reconnecting attempt while Android client catching server termination event, out of sync takes place yielding collision with already terminated connection. I adjusted the keepalive timeout and hope this should rectify it.

Otherwise, one notable thing I performed it's that I updated kernel to 7.1.4 from 7.1.3 yesterday, although I doubt ovpn module had new issue introduced as a result, given the kernel change log doesn't reference anything about ovpn module.

I will keep an eye on the log and notifications over the coming days and see if I can reproduce any bug.

I will update this ticket.

**Comment by cron2** [comment]
There is no indication in the log lines you have posted that anything is getting out of sync here.  In one case the client sent an EEN, and in the other case the client timed out and the kernel DCO sent up a notification telling userland "client expired", which was handled accordingly (different `reason`).

The only message that might be a bit confusing here is the `ovpn_handle_peer: received data for a non-existing peer 1`, but that one can be ignored (userland tells the kernel "hey, kill peer 1", kernel sends userland a "peer 1 was killed (because userland asked for it)" - which is something of a confirmation - but at this point userland has already forgotten about this client).

**Comment by schwabe** [comment]
(Hid the message from @InputOutputZ as they are not related to this issue)

**Comment by InputOutputZ** [comment]
> (Hid the message from [@InputOutputZ](https://github.com/InputOutputZ) as they are not related to this issue)

ok, I'm not sure if there is any other kind of bug but if you want I can open separate issue, let me know, with thanks.

**Comment by cron2** [comment]
> > (Hid the message from [@InputOutputZ](https://github.com/InputOutputZ) as they are not related to this issue)
> 
> ok, I'm not sure if there is any other kind of bug but if you want I can open separate issue, let me know, with thanks.

This issue is about "openvpn crashes because it gets out of sync with DCO", which got fixed, both for 2.7 and for 2.6

What should go here is reports about
 - crashes
 - status file growing unbounded, because new peers get added, but old peers are not expired
 - obviously-incorrect attributions between actions by peer X and log lines for peer Y

**Comment by ordex** [comment]
The patch posted here[1] should ultimately fix this issue for good.

[1] https://gerrit.openvpn.net/c/openvpn/+/1835
